### ISSUE TITLE
switch @rel to @role and apply to all data elements

### ISSUE THREAD

**Issue by mamund** [uber-hypermedia/specification#17]
to clarify semantic uses for both transition and value elements, switch from @rel to @role and apply to all elements. 

_NOTE: THIS IS A BREAKING CHANGE_

**Comment by mamund** [comment]
@inadarei 

ok, got a bit nervous as i was researching the `role` attribute from the XLink spec[1] (where i pulled it in support of my idea for updating `rel`. first, for XLink, the `role` is a _single_ URI whereas `rel` supports multiple URIs[2].

i don't want to lose the multi-URI aspect AND i still want this attribute to be used for both data and hyperlink versions of the `data` element. 

so, some options:
 * `class` (current defs don't allow URIs)
 * `role` (just overload the definition, not many ppl use `XLink@role` anyway)
 * `kind`, `semantics` (invent a new word that seems close)
 * `rel` (just use the one ppl recognize but give it new def -- applies to data, not just links. can be more than relationship info)
 * something _else_ (i'm open)

comments?


[1] http://www.w3.org/TR/xlink/#link-semantics
[2] http://www.w3.org/TR/html5/document-metadata.html#attr-link-rel

**Comment by inadarei** [comment]
I think, in Hypermedia space 'link relation" is such well-established term that if we call `rel` **anything**else it will quickly become awkward to keep explaining: "attribute X is actually link relation type, but we are calling it something else".

Two choices I would recommend:

> Keep calling "rel" what it is, for non-URL data elements introduce "type".

The drawback of this approach is that we now have two attributes, for seemingly very similar purpose and that takes away from the very small footprint of UBER. However, the huge benefit of this approach is:

1. It makes the change backwards-compatible
1. we can use original meaning of `rel`

My 2nd choice would be: expanding the meaning of "rel"
My 3rd choice sould be: using "type" for the purpose. I think `type` sounds more natural than `kind` since it has one meaning, unless we want to fill UBER with kindness :)

**Comment by mamund** [comment]
@inadarei 

yeah - i should have included `type` in the list of possibles. HTML uses that as a hint for media-types, tho (sigh...)

i say we just _leave it as `rel`, expand the meaning (which actually would bring it in line w/ common usage, IMO) AND allow it to be used for `data` elements that are just semantic info (not hyperlinks).

**Comment by inadarei** [comment]
Good catch, forgot that `type` already has a different meaning.

Expanding the meaning of `rel` sounds good. Let's do that.

**Comment by mamund** [comment]
cool. will work out the prose as soon as we sort out these two pending merges.

**Comment by inadarei** [comment]
I merged the first one and that created merge conflict for the second one, but will resolve it later today and merge it, if that's cool.

**Comment by mamund** [comment]
all cool. i'll stand down until this is sorted. if it starts to get messy on the manual merge, just toss it back to me and i'll sort it out.

**Comment by benhamill** [comment]
I, too, like expanding the meaning of `rel`. There are other media types that do this at least implicitly (HAL comes to mind).

Maybe we can find another way to fill UBER with kindness. :heartbeat:

**Comment by mamund** [comment]
@benhamill 

all cool on the `rel` front. i was _trying_ to be true and "pure" w/ `rel`'s history and still support the features we needed but it seems pretty daunting and not worth trying to create something new. so we'll continue w/ `rel` and work on being explicit in it's use/meaning.

not sure about the "kindness" line, but hopefully that's meant as a good thing ;)

**Comment by benhamill** [comment]
Heh. It was just a reference to @inadarei's joke about kind having more than one meaning.

**Comment by mamund** [comment]
@benhamill 

ROFL! got it.

**Comment by inadarei** [comment]
I love the expanded meaning of "rel", I think it makes a lot of sense. I have couple questions that may need further clarification or just a quick discussion, however. Both of them relate to standardization of rel attributes. Many rels are application or industry-specific, but there're also handful that are generic. Standardizing those allows for interoperability (or as I prefer to call it: "recognizability of affordances"). We should make sure there's clear understanding of how/where expanded rels can be standardized or used from standards.

1. Usage of rels that were standardized for links (actual URLs) in non-URL context
    
    There're a handful of link relations ("author", "item" and "collection" come to mind immediately) that will be tempting for usage in non-URL contexts. However, the standards for these rels are only defined in the context of URLs. For instance, the definition of "item" reads: 
    > The target IRI points to a resource that is a member of the collection represented by the context IRI.

    Formally speaking "item" is not defined outside the context of a URL.

2. Where will non-URL "rels" be standardized?

     Say I come up with a "rel" that makes ton of sense in many use-cases, but it's not a specifically URL-oriented relation: where would I standardize such things?

## Proposed Answer

Following is my proposed solution to the challenge, but also very much looking forward to other suggestions:

I think the language, in UBER, that allows usage of "rel" for non-URL contexts should explicitly state that the data labeled with such rel attributes MUST be considered as a remote resource embedded in the document. Meaning the following two things MUST be equivalent and interchangable:

Link-based resource representation:

```xml
<data name="Collection of Users" 
      rel="http://api.example.com/rels/users" 
      url="http://api.example.com/users{?position,gender,age}">
  <data name="Madilynn Sawyer" rel="item" url="http://api.example.com/users/1"/>
  <data name="Kaylee Nguyen" rel="item" url="http://api.example.com/users/2"/>
  <data name="Marc Watkins" rel="item" url="http://api.example.com/users/3"/>
  <data name="Jay Best" rel="item" url="http://api.example.com/users/4"/>
  <data name="Cynthia Mcconnell" rel="item" url="http://api.example.com/users/5"/>
  <data name="Beatrice Estrada" rel="item" url="http://api.example.com/users/6"/>
  <data name="Mathew Herring" rel="item" url="http://api.example.com/users/7"/>  
</data>
```

Equivalent resource representation with embedded values:

```xml
<data name="Collection of Users" 
      rel="http://api.example.com/rels/users" 
      url="http://api.example.com/users{?position,gender,age}">
  <data rel="item">
    <data name="fullname">Madilynn Sawyer</data> 
    <data name="position">engineer</data>
    <data name="gender">female</data>
    <data name="age">34</data>
  </data> 
  <data rel="item">
    <data name="fullname">Kaylee Nguyen</data> 
    <data name="position">project manager</data>
    <data name="gender">female</data>
    <data name="age">52</data>
  </data>   
  <data rel="item">
    <data name="fullname">Marc Watkins</data> 
    <data name="position">analyst</data>
    <data name="gender">male</data>
    <data name="age">29</data>
  </data>   
  <data rel="item">
    <data name="fullname">Jay Best</data> 
    <data name="position">engineer</data>
    <data name="gender">male</data>
    <data name="age">23</data>
  </data>   
  <data rel="item">
    <data name="fullname">Cynthia Mcconnell</data> 
    <data name="position">director</data>
    <data name="gender">female</data>
    <data name="age">41</data>
  </data>   
  <data rel="item">
    <data name="fullname">Beatrice Estrada</data> 
    <data name="position">engineer</data>
    <data name="gender">female</data>
    <data name="age">24</data>
  </data>   
  <data rel="item">
    <data name="fullname">Mathew Herring</data> 
    <data name="position">designer</data>
    <data name="gender">male</data>
    <data name="age">45</data>
  </data>   
</data>
```

### The above solution, in essence, means the following:

1. UBER has highly modular design and the way UBER documents should be modeled is that we should assume that any <data> branch could be externalized as a remote resource representation, if needed.

2. Using "rels" with non-URL data elements is OK because when we do it we view that data element as an embedded representation of a resource representation. Therefore the semantics of the "rel" used should be equivalent to what it would mean if the affected `<data>` element were a remote resource. If the data element affected can not be represented as a remote resource then "rel" attribute SHOULD NOT be used. The meaning of a "rel" attribute SHOULD retain the original spirit of the definition.

**Comment by inadarei** [comment]
FWIW, one of the things I love about UBER is exactly point #1: "any data branch can be externalized at any time if needed" because that makes UBER a hypermedia type that is very friendly to [Linked APIs](http://linkedapis.org/). 

I don't think this trait of UBER is explicitely stated in the spec, however, but it seems important for the decision of allowing "rel" to have expanded meaning.

**Comment by benhamill** [comment]
@inadarei: I have a question about your example. If each user item in your collection was only a partial representation and you wanted to provide a link to get the full representation, how would _you_ do it? UBER allows for several answers, AFAICT, so I'm interested in what your instinct is.

**Comment by mamund** [comment]
<snip>
 data labeled with such rel attributes MUST be considered as a remote resource embedded 
</snip>
really don't want to add this MUST. 

not sure why you want to REQUIRE this when marking elements w/ semantic markers. it will, i suspect, lead to ppl *not* adding semantic affordances to data elements.  i certainly will NOT be making any of this "MUST be an embedded remote resource" kind of designs. 

this sounds way to over-constraining and i don't know why you want to do this.

help me out.

**Comment by inadarei** [comment]
@benhamill I would probably do something like:

```xml
  <data rel="item" url="http://api.example.com/users/1>
    <data name="fullname">Madilynn Sawyer</data> 
    <data name="position">engineer</data>
    <data name="gender">female</data>
    <data name="age">34</data>
  </data> 
```

**Comment by inadarei** [comment]
@mamund,

I hear you and maybe what I suggested is a bad solution, but the problem itself is: how to address two use-cases that will emerge as soon as we say "rel can also be used for non-URL elements":

1. People will start using standard rels (such as: "item", "collection", "author" etc.) for non-URL contexts, but those were standardized only for URLs.
2. If people come up with "rels" for non-URL-based elements: where would they standardize those and how would people tell the difference? Through checking the actual definition in the standards (assuming those will indicate if the rels are URL- or non-URL ones)?

Curious what your thoughts are on those.

**Comment by mamund** [comment]
On, staying from perceived use cares helps.

Let's talk about those and see what possible solutions are available.

Looking for a POV on what is desired behavior, what is the suspected harm involved, what level of constraint we ember to impose on everyone forever on order to get the desired  behavior and/or urgent the expect harm.

**Comment by inadarei** [comment]
Awesome. OK so let's see example of the Problem1 (people using link rels for non-URL data elements). What is your take on seeing API designs with UBER that have messages that contain things like the following:

```xml
<data name="Shopping Cart" rel="shopping-cart">
  <data rel="item">
    <data name="name">Bose QuietComfort 25 Headphones, Black</data> 
    <data name="SKU">B00M1NEUKK</data>
    <data name="quantity">2</data>
    <data name="item-price">299.00</data>
  </data> 
  <data rel="item">
    <data name="name">Micca MB42X Bookshelf Speakers</data> 
    <data name="SKU">B00E7H8GG2</data>
    <data name="quantity">1</data>
    <data name="item-price">79.99</data>
  </data>   
</data>
```

where the definition of `item` link rel at IANA is: 

> The target IRI points to a resource that is a member of the collection represented by the context IRI

Is this:

1. Operator error (just don't do it)
2. Not an issue at all (spirit of "item" is retained so who cares)
3. Yeah, worth discussing further

**Comment by benhamill** [comment]
IMO, it's number 2 on that list.

**Comment by mamund** [comment]
@inadarei : 
yeah, not sure i see trouble here. can you expand?

**Comment by inadarei** [comment]
There is not much to expend, actually. I was just curious if you thought it could be trouble but sounds like the unanimous response is: "no trouble", so that answers my question :)

**Comment by inadarei** [comment]
What about the original Question Number Two?

Do you think there will be `rel`s created that make no sense for URL-oriented context? Will it cause problem in standardization (since IANA won't accept such rel definitions) or: do you expect that most "rels" will have portable-enough semantic meaning that they will always make sense in URL-based context, hence: no issue here, as well?

**Comment by mamund** [comment]
will there be ones created that won't be standardized? absolutely. do we want to try to _prevent_ that from happening? no. 

RFC5988 has solid guidance on how to handle non-registered values for `rel` -- the creation of URIs. and that's the guidance we should be passing along to authors of UBER docs (e.g. "if you're not using a registered value for `rel` -- IANA, microformat, DublinCore, etc. -- then use a URI per RFC5988").

**Comment by inadarei** [comment]
Cool. Sounds good enough to me. Thank you!
